#!/bin/bash

PATH=$PATH:/usr/local/mysql/bin

PRIVS_LABELS="Select_priv,Insert_priv,Update_priv,Delete_priv,Create_priv,Drop_priv,Process_priv,References_priv,Index_priv,Alter_priv,Show_db_priv,Create_tmp_table_priv,Lock_tables_priv,Create_view_priv,Show_view_priv,Create_routine_priv,Alter_routine_priv,ssl_cipher,x509_issuer,x509_subject"
PRIVS_VALUES="'Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','','',''"

read    -p "developer username: " USER
read -s -p "root mysql password: " ROOTPSWD
echo

mysql      -u root -p$ROOTPSWD -e "insert into user (Host,User,Password,$PRIVS_LABELS) values ('%','$USER',PASSWORD('$USER'),$PRIVS_VALUES);" mysql 2>/dev/null
mysqladmin -u root -p$ROOTPSWD reload 2>/dev/null
